# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96088eea38e2b2b9b40771a8c80b6c6e5d1990f682ce64c40a7708cda4bc373252c699ee061a877d59eaefd7ae7d847f4a1982adbe4c88713dc3622a66134583

test:
  secret_key_base: 7505e0ff2fcd8289f7b73202c7487b0aaf3aa12883dc44381768027901c795a508960724e3e7379083c29693d546042539a536a0e17778b08ecc8712783d0f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
